### ISSUE TITLE
Nut van variabelen?

### ISSUE THREAD

**Issue by RichardRam87** [itsdexter66/MythesCode#8]
Je hebt feedback gekregen van **RichardRam87**
op:
```c
[SerializeField]
    private bool activityObjectTrue,
                 activityObjectFalse; 
```

URL: https://github.com/itsdexter66/MythesCode/blob/master/Mythe/Assets/Scripts/InvisibleColliders/OnCollSetActive.cs

Feedback: Wat is het nut van deze variabelen? Zijn die niet gewoon uit het gameobject te lezen?[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"7560ac6bc9482246bafd24f9206d496809bcf59e","path":"Mythe/Assets/Scripts/InvisibleColliders/OnCollSetActive.cs","reviewer":"RichardRam87"}')

**Comment by itsdexter66** [comment]
Sem heeft de issue gefixt
